version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/cmd/token-injector"
    schedule:
      interval: "daily"
    assignees:
      - "ealebed"
  - package-ecosystem: "gomod"
    directory: "/cmd/token-injector-webhook"
    schedule:
      interval: "daily"
    assignees:
      - "ealebed"

  - package-ecosystem: "docker"
    directory: "/cmd/token-injector"
    schedule:
      interval: "daily"
    assignees:
      - "ealebed"
  - package-ecosystem: "docker"
    directory: "/cmd/token-injector-webhook"
    schedule:
      interval: "daily"
    assignees:
      - "ealebed"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "ealebed"

  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "ealebed"
